import type { Recipe } from "@/components/filters/recipe-filters"

export const recipes: Recipe[] = [
  {
    id: "r1",
    title: "Fried Rice with Meat and Vegetables",
    price: 23,
    category: "Rice",
    image: "/images/dishes/people-sharing-salad.jpg",
    spicy: true,
  },
  {
    id: "r2",
    title: "Medium Beef and Chili Soup",
    price: 12,
    category: "Soup",
    image: "/images/dishes/friends-toasting-drinks.jpg",
    spicy: true,
  },
  {
    id: "r3",
    title: "Meat Mix with Fruit Soup",
    price: 14,
    category: "Soup",
    image: "/images/dishes/family-brunch-spread.jpg",
  },
  {
    id: "r4",
    title: "Fruit Salad with Mixed Fruit",
    price: 8,
    category: "Salad",
    image: "/images/dishes/people-sharing-salad.jpg",
    vegan: true,
  },
  {
    id: "r5",
    title: "Vegetable Salad with Mixed Fruit Salad",
    price: 10,
    category: "Salad",
    image: "/images/dishes/people-sharing-salad.jpg",
    vegan: true,
  },
  {
    id: "r6",
    title: "Butter Bread with Mixed Vegetables",
    price: 9,
    category: "Bread",
    image: "/images/dishes/family-brunch-spread.jpg",
    vegan: true,
  },
  {
    id: "r7",
    title: "Noodles with Meat and Curry",
    price: 11,
    category: "Noodles",
    image: "/images/dishes/chef-plating-pasta.jpg",
    spicy: true,
  },
  {
    id: "r8",
    title: "Whole Wheat Bread with Avocado Sauce",
    price: 8,
    category: "Bread",
    image: "/images/dishes/chef-plating-pasta.jpg",
    vegan: true,
  },
  {
    id: "r9",
    title: "Watermelon Mix Salad",
    price: 7,
    category: "Salad",
    image: "/images/dishes/people-sharing-salad.jpg",
    vegan: true,
  },
]
